### ISSUE TITLE
Error when installing role on OSX

### ISSUE THREAD

**Issue by yardbirdsax** [gantsign/ansible-role-oh-my-zsh#106]
When installing the role on OSX, the following error is received:

```
TASK [gantsign.oh-my-zsh : install dependencies] ****************************************************************************************************************************************************************************************
failed: [localhost] (item=git) => {"ansible_loop_var": "item", "changed": false, "item": "git", "msg": "Error: Running Homebrew as root is extremely dangerous and no longer supported.\nAs Homebrew does not drop privileges on installation you would be giving all\nbuild scripts full access to your system."}
```

Example configuration:

```
- role: gantsign.oh-my-zsh
      users:
        - username: "{{ user_name }}"
          plugins:
            - git
            - kube-ps1
            - vscode
```
