### ISSUE TITLE
Prexis the users variable

### ISSUE THREAD

**Issue by yodatak** [gantsign/ansible-role-oh-my-zsh#118]
Hi its could be interesting to prefix the users variables beacuase its way too generic ^^

**Comment by freemanjp** [comment]
@yodatak, thanks for the feedback. `users` is a common convention, used by many roles, for user-specific config (so you can group user specific config together and avoid repetition of the username) e.g.:

```yaml
users:
    - username: joe
      role1_var1: eg
      role2_var1: eg
      role3_var1: eg
      role3_var2: eg
    - username: jill
      role3_var1: eg
      role3_var2: eg
```

The variables `users` and `username` aren't prefixed, but the variables under each user are.
