### ISSUE TITLE
how to install ohmyzsh for users using loop?

### ISSUE THREAD

**Issue by Gictorbit** [gantsign/ansible-role-oh-my-zsh#143]
hello, I just want to install `oh-my-zsh` for multiple users, so how can I do this?
Here is my Ansible playbook, but it throws an error (item not found) 

```yaml
- name: setup ohmyzsh for users
  hosts: all
  vars:
    userlist:
      - username: "viktor"
        password: "viktor123"
  become: yes
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ item.username }}"
          oh_my_zsh:
            theme: gnzh
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - docker
      loop: "{{ userlist }}"

```

**Comment by freemanjp** [comment]
Hi @Gictorbit, unfortunately, `loop` doesn't work with Ansible roles (only with tasks). Try the following instead:

```yaml
- name: setup ohmyzsh for users
  hosts: all
  vars:
    userlist:
      - username: "viktor"
        password: "viktor123"
  become: yes
  pre_tasks:
    - name: build oh_my_zsh_users 
      set_fact:
        oh_my_zsh_users: '{{ (oh_my_zsh_users | default([])) + [oh_my_zsh_user] }}'
      vars:
        oh_my_zsh_user:
          username: '{{ item.username }}'
          oh_my_zsh:
            theme: gnzh
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - docker
      loop: '{{ userlist }}'
  roles:
    - role: gantsign.oh-my-zsh
      users: '{{ oh_my_zsh_users }}'
```
