### ISSUE TITLE
change in theme/plugins doesn't make it to .zshrc

### ISSUE THREAD

**Issue by mircsicz** [gantsign/ansible-role-oh-my-zsh#145]
Not sure if this is an expected behaviour, but after changing the gefault theme to "gnzh" and running the role/playbook again I can't see a change on my machines .zshrc...

Expected behaviour would be for it to be like this:

`ZSH_THEME="XYZ" 
`
changes to whatever I set in
```
    - role: gantsign.oh-my-zsh
      users:
        - username: '{{remoteuser}}'
          oh_my_zsh:
          theme: gnzh
          plugins:
            - git
```

sadly same is true if I add more plugins to the above shown array...

**Comment by mircsicz** [comment]
maybe this helps:

TASK [gantsign.oh-my-zsh : install dependencies] ********************************************************************
ok: [one-bh-xw]
ok: [one-bh-tc]
ok: [one-bh-x1]
ok: [one-bn-f36]

TASK [gantsign.oh-my-zsh : clone oh-my-zsh for users] ***************************************************************
ok: [one-bh-tc] => (item=mircsicz)
ok: [one-bh-xw] => (item=mircsicz)
ok: [one-bh-x1] => (item=mircsicz)
ok: [one-bn-f36] => (item=mircsicz)

TASK [gantsign.oh-my-zsh : set permissions of oh-my-zsh for users] **************************************************
ok: [one-bh-xw] => (item=mircsicz)
ok: [one-bh-x1] => (item=mircsicz)
ok: [one-bh-tc] => (item=mircsicz)
ok: [one-bn-f36] => (item=mircsicz)

TASK [gantsign.oh-my-zsh : set default shell for users] *************************************************************
ok: [one-bh-tc] => (item=mircsicz)
ok: [one-bh-x1] => (item=mircsicz)
ok: [one-bh-xw] => (item=mircsicz)
ok: [one-bn-f36] => (item=mircsicz)

TASK [gantsign.oh-my-zsh : write .zshrc for users] ******************************************************************
ok: [one-bh-tc] => (item=mircsicz)
ok: [one-bh-xw] => (item=mircsicz)
ok: [one-bh-x1] => (item=mircsicz)
ok: [one-bn-f36] => (item=mircsicz)

TASK [gantsign.oh-my-zsh : console setup for Debian family distributions] *******************************************
skipping: [one-bh-tc]
skipping: [one-bh-x1]
skipping: [one-bh-xw]
skipping: [one-bn-f36]

**Comment by freemanjp** [comment]
Hi @mircsicz it looks like an issue with the indentation of your role config. The config should be:
```
    - role: gantsign.oh-my-zsh
      users:
        - username: '{{remoteuser}}'
          oh_my_zsh:
            theme: gnzh
            plugins:
              - git
```
Notice how `theme:` and `plugins:` are indented so they're children of  `oh_my_zsh:` rather than siblings.
