### ISSUE TITLE
Missing acl package in oh_my_zsh_dependencies

### ISSUE THREAD

**Issue by Wolfeg** [gantsign/ansible-role-oh-my-zsh#159]
If `acl` package is missing on system, ansible cant use `setfacl`, so trying chmod instead, that cant be used on another unpriveleged user with template module. More [here](https://docs.ansible.com/ansible-core/2.13/user_guide/become.html#risks-of-becoming-an-unprivileged-user). After installing that package on system, everything works fine

**Comment by freemanjp** [comment]
@Wolfeg thanks for reporting this issue. Sorry for the late reply. If I understand correctly, you're trying to run the role using an unprivileged user. Unfortunately, I don't think that'll work, the role was designed to be run by a user with `root` privileges to install Oh My Zsh for multiple users. In hindsight, it would probably have been better to just install Oh My Zsh for the current user without requiring `root` privileges, but that would be too big a breaking change at this point.

**Comment by Wolfeg** [comment]
I have main playbook like this:
```
---
- hosts: all
  **become: yes**
  roles:
    - ssh-users
    - sshd-config
    - tz-data
    - cloudalchemy.node_exporter
```
inside ssh-users role i have task:
```
- name: Installing oh my zsh
  include_role:
    name: gantsign.oh-my-zsh
```
and inside ssh-users role defaults:
```
users:
  - username: user1
    admin: yes
    oh_my_zsh:
      theme: fino-time
      plugins:
          - git
          - z
      update_mode: auto
      update_frequency: 0
  - username: user2
    admin: yes
    oh_my_zsh:
      theme: fino-time
      plugins:
          - git
          - z
      update_mode: auto
      update_frequency: 0
  - username: root
    oh_my_zsh:
      theme: fino-time
      plugins:
          - git
          - z
      update_mode: auto
      update_frequency: 0
```
I can't remember what error gave me ansible, that was something about acl. I run playbooks under user with sudo group.
