### ISSUE TITLE
chmod: invalid mode

### ISSUE THREAD

**Issue by stefanpl** [gantsign/ansible-role-oh-my-zsh#175]
Hi 👋

I'm trying to run this role against a Ubuntu 22.04.4 LTS instance:

```yaml
  roles:
    - role: gantsign.oh-my-zsh
      become: true
      tags:
        - shell_setup
      users:
        - username: nwon
          oh_my_zsh:
            theme: maran
            plugins:
              - git
```

Getting this error:

```
TASK [gantsign.oh-my-zsh : write .zshrc for users] ****************************************************************************
fatal: [resolvio-testing-new]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:nwon:rx:allow’\nTry 'chmod --help' for more information.\n}). For information on working around this, see https://docs.ansible.com/ansible-core/2.16/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user"}
```

… where I think the interesting bit is:

`chmod: invalid mode: ‘A+user:nwon:rx:allow’`

FWIW, `chmod --version` yields `chmod (GNU coreutils) 8.32`. But the syntax looks pretty odd, so I don't think it's a version problem.

Do you have any idea what's going on here? Thanks a lot for any insights 🙏
